# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
      - 192.168.1.74/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8]
  version: 2
